channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=23.3.2
- pip:
  - mlflow==2.10.0
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - gmpy2==2.1.2
  - matplotlib==3.8.2
  - numpy==1.26.3
  - packaging==23.2
  - pandas==2.2.0
  - pyyaml==6.0.1
  - scikit-learn==1.4.0
  - scipy==1.12.0
  - torch==2.1.2.post300
name: mlflow-env
